Marista.Admin/Controllers/MarketingMaterialController.cs
using Marista.Admin.Filters;
using Marista.Common.ViewModels;
using Marista.DL;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Marista.Admin.Controllers
{
    [AdminAuthorize]
    public class MarketingMaterialController : BaseController
    {
        private readonly MarketingMaterialService _ms = new MarketingMaterialService();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (this.UserData == null )
            {
                filterContext.HttpContext.Response.Redirect(Url.Action("Login", "User"), true);
                return;
            }
            base.OnActionExecuting(filterContext);
        }

        public async Task<ActionResult> Index()
        {
            var materials = await _ms.Get();
            ViewBag.Level = this.UserData.LevelId;
            return View(materials);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MarketingMaterialVM m)
        {

            if (m.Title != "" && Request.Files.Count == 1)
            {
                m.FileName = Request.Files[0].FileName;
                MemoryStream target = new MemoryStream();
                Request.Files[0].InputStream.CopyTo(target);
                m.Content = target.ToArray();
                await _ms.Create(m);
            }
            return RedirectToAction("Index");
        }



        public async Task<ActionResult> Get(int id)
        {
            var b = await _ms.Get(id);
            if (b == null)
            {
                return RedirectToAction("Index");
            }
            var fc = new FileContentResult(b.Content, "application/octet-stream");
            fc.FileDownloadName = b.FileName;
            return fc;

        }

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _ms.Delete(id);
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Marista.Admin/Views/MarketingMaterial/Index.cshtml
@model IList<Marista.Common.ViewModels.MarketingMaterialVM>

@{
    ViewBag.Title = "Index";
}

<h2>Marketing material</h2>
@if (ViewBag.Level == 1)
{

    using (Html.BeginForm("Create", "MarketingMaterial", FormMethod.Post,
                                                            new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <div class="form-group">
                <label class="control-label col-md-2">Title:</label>
                <div class="col-md-10">
                    <input type="text" name="Title" class="form-control" id="tbTitle" />

                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">File:</label>
                <div class="col-md-10">
                    <input type="file" name="file" class="form-control" id="fuFile" />

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success btn-lg" onclick="return validate()" />
                </div>
            </div>
        </div>


    }

}

<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th width="400">File</th>
                <th width="100"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var b in Model)
            {
                <tr>
                    <td>@b.Title</td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="@Url.Action("Get", new { id = b.MarketingMaterialId})" class="btn btn-default" title="View"><i class="glyphicon glyphicon-search"></i></a>
                            @b.FileName
                        </div>
                    </td>
                    <td>
                        <a href="@Url.Action("Delete", new { id = b.MarketingMaterialId})" class="btn btn-default" title="View"><i class="glyphicon glyphicon-remove-sign"></i></a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    function validate() {
        if ($("#tbTitle").val() === "") {
            alert("Please, enter title");
            return false;
        }
        if ($("#fuFile").val() === "") {
            alert("Please, select file");
            return false;
        }

        return true;
    }
</script>