Marista.Admin/Controllers/CouponController.cs
using Marista.Admin.Filters;
using Marista.Common.ViewModels;
using Marista.DL;
using PagedList;
using SoundInTheory.DynamicImage.Fluent;
using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Marista.Admin.Controllers
{
    [AdminAuthorize]
    public class CouponController : BaseController
    {
        private readonly CouponService _cs = new CouponService();
        private readonly ProductService _ps = new ProductService();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (this.UserData == null || (this.UserData != null && this.UserData.LevelId != 2))
            {
                filterContext.HttpContext.Response.Redirect(Url.Action("Login", "User"), true);
                return;
            }
            base.OnActionExecuting(filterContext);
        }

        public async Task<ActionResult> Index(string q, int? page, int? createdId)
        {
            var coupons = await _cs.Get(q);
            ViewBag.SearchQuery = q ?? string.Empty;
            ViewBag.CreatedId = createdId;
            return View(coupons.ToPagedList(page ?? 1, 20));
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var c = new CouponVM();
            c.Expires = DateTime.Now.AddDays(30); // default expiration date
            c.ForAll = true; //select for all products by default
            await PopulateSelectLists();
            return View(c);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CouponVM c)
        {
            if (ModelState.IsValid)
            {
                // check if only one of the possible options has been selected
                if (!c.IsOnlyOneOptionSelected)
                {
                    ModelState.AddModelError(string.Empty, "Only one of the options should be selected");
                    await PopulateSelectLists();
                    return View(c);
                }

                var uniqueId = GenerateUniqueId();

                while (await _cs.UniqueIdExisting(uniqueId))
                {
                    uniqueId = GenerateUniqueId();
                }

                c.UniqueId = uniqueId;
                c.SiteUserId = UserData.UserId;
                c.Img = await GenerateImage(uniqueId, c.Expires, c.Discount);
                c = await _cs.Create(c);

                return RedirectToAction("Index", new { createdId = c.CouponId });
            }

            await PopulateSelectLists();
            return View(c);
        }

        public async Task<ActionResult> Download(int id)
        {
            var coupon = await _cs.Get(id);
            var img = coupon.Img;

            return File(img, "image/jpg", "coupon-number-" + coupon.UniqueId + ".jpg");
        }

        public async Task<ActionResult> SwitchUsed(int id)
        {
            await _cs.SwitchUsed(id);
            return RedirectToAction("Index");
        }

        //Helpers
        private async Task<byte[]> GenerateImage(string uniqueId, DateTime expirationDate, int discount)
        {
            var templateImagePath = "~/Content/Images/coupon-template.jpg";
            var generatedImagePath = $"~/Content/Images/generated-coupon-{uniqueId}.jpg";

            CompositionBuilder builder = new CompositionBuilder() // generating the image
                           .WithLayer(LayerBuilder.Image
                                           .SourceFile(Server.MapPath(templateImagePath)))
                           .WithLayer(LayerBuilder.Text.Text("Coupon number: " + uniqueId)
                                           .Anchor(SoundInTheory.DynamicImage.AnchorStyles.TopLeft)
                                           .ForeColor(SoundInTheory.DynamicImage.Color.FromArgb(160, 10, 10, 10))
                                           .FontSize(30)
                                           .FontBold())
                           .WithLayer(LayerBuilder.Text.Text("Expires: " + expirationDate.ToString())
                                           .Anchor(SoundInTheory.DynamicImage.AnchorStyles.BottomLeft)
                                           .ForeColor(SoundInTheory.DynamicImage.Color.FromArgb(160, 10, 10, 10))
                                           .FontSize(20)
                                           .FontBold())
                           .WithLayer(LayerBuilder.Text.Text("Discount: " + discount)
                                           .Anchor(SoundInTheory.DynamicImage.AnchorStyles.TopRight)
                                           .ForeColor(SoundInTheory.DynamicImage.Color.FromArgb(160, 10, 10, 10))
                                           .FontSize(20)
                                           .FontBold())
                            .ImageFormat(SoundInTheory.DynamicImage.DynamicImageFormat.Jpeg);

            builder.SaveTo(Server.MapPath(generatedImagePath)); // Saving the generated image with the unique id on it.

            var generatedImageFileInfo = new FileInfo(Server.MapPath(generatedImagePath));
            var imageBytes = new byte[generatedImageFileInfo.Length];

            using (var fileStream = generatedImageFileInfo.OpenRead())
            {
                await fileStream.ReadAsync(imageBytes, 0, imageBytes.Length);
            }

            generatedImageFileInfo.Delete();

            return imageBytes;
        }


        private async Task PopulateSelectLists()
        {
            ViewBag.HCategories = new SelectList(await _ps.GetHCategories(), "HCategoryId", "CategoryName");
            ViewBag.VCategories = new SelectList(await _ps.GetVCategories(), "VCategoryId", "CategoryName");
            ViewBag.Products = new SelectList(await _ps.Get(), "ProductId", "Name");
        }

        private string GenerateUniqueId()
        {
            var random = new Random(Guid.NewGuid().GetHashCode());
            int randomNumber = random.Next(1, 999999999);
            return randomNumber.ToString().PadLeft(10, '0');
        }
    }
}

Marista.Admin/Views/Coupon/Create.cshtml
@model Marista.Common.ViewModels.CouponVM
@{
    ViewBag.Title = "Create a Coupon";
}
@section styles {
<link href="~/Content/bootstrap-datetimepicker-build.min.css" rel="stylesheet" />
}
@section scripts {
    <script src="~/Scripts/moment.min.js"></script>

    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('input[type=datetime]').datetimepicker();
        });
    </script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script>
        $(function () {
            var $checkBox = $('.checkbox');

            $checkBox.on('change', function (e) {

                // enable a corresponding select list:
                var $select = $('#' + $(this).attr('id') + '-list');

                if ($(this).is(':checked')) {
                    $select.removeAttr('disabled');
                    $('.checkbox').not(this).prop('checked', false).trigger('change');
                } else {
                    $select.attr('disabled', 'disabled');
                }
            });
        });
    </script>
}

@using (Html.BeginForm("Create", "Coupon", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create new coupon</h4>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Expires, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Expires, htmlAttributes: new { @class = "form-control", type = "datetime" })
                @Html.ValidationMessageFor(model => model.Expires, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-1">
                <input class="checkbox" type="checkbox" id="horizontal" />
            </div>
            <div class="col-md-9">
                @Html.DropDownList("HCategoryId", (SelectList)ViewBag.HCategories, optionLabel: "Select Horizontal Category...", htmlAttributes: new { @class = "form-control", id = "horizontal-list", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.HCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-1">
                <input class="checkbox" type="checkbox" id="vertical" />
            </div>
            <div class="col-md-9">
                @Html.DropDownList("VCategoryId", (SelectList)ViewBag.VCategories, optionLabel: "Select Vertical Category...", htmlAttributes: new { @class = "form-control", id = "vertical-list", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.VCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-1">
                <input class="checkbox" type="checkbox" id="product" />
            </div>
            <div class="col-md-9">
                @Html.DropDownList("ProductId", (SelectList)ViewBag.Products, optionLabel: "Select a Product...", htmlAttributes: new { @class = "form-control", id = "product-list", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ForAll, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.ForAll, htmlAttributes: new { @class = "checkbox" })
                @Html.ValidationMessageFor(model => model.ForAll, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Discount, htmlAttributes: new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success btn-lg" />
            </div>
        </div>
    </div>
}

<div class="sub-footer row">
    <div class="col-sm-12">
        <a href="@Url.Action("Index")" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-backward"></i> Back to the list of products</a>
    </div>
</div>

Marista.Admin/Views/Coupon/Index.cshtml
@model PagedList.IPagedList<Marista.Common.ViewModels.CouponVM>

@{
    ViewBag.Title = "Coupons";
}

<h2><a href="@Url.Action("Index")">@ViewBag.Title</a></h2>

<div class="row filters-panel">
    <div class="col-sm-3">
        <a href="@Url.Action("Create")" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Create new coupon</a>
    </div>
    <div class="search-bar col-sm-4 col-sm-offset-5">
        <form action="@Url.Action("Index")" method="get" class="form-inline">
            <div class="form-group">
                <input type="search" name="q" value="@ViewBag.SearchQuery" class="form-control" placeholder="Search Coupons" />
                <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-filter"></i></button>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                @*<th></th>*@
                <th width="64">UniqueId</th>
                <th>For</th>
                <th width="50">Expiration date</th>
                <th width="50">Discount</th>
                @*<th width="40">Used</th>
                <th width="60">Download Coupon</th>*@
            </tr>
        </thead>
        <tbody>
            @foreach (var c in Model)
            {
                <tr id="coupon-@c.CouponId" class="@(c.CouponId == ViewBag.CreatedId ? "success" : "")">
                    @*<td>
                        <div class="btn-group btn-group-sm">
                            <a href="@Url.Action("Details", new { id = c.CouponId })" class="btn btn-default" title="View"><i class="glyphicon glyphicon-search"></i></a>
                            <a href="@Url.Action("Edit", new { id = c.CouponId })" class="btn btn-info" title="Edit"><i class="glyphicon glyphicon-edit"></i></a>
                        </div>
                    </td>*@
                    <td>
                        @c.UniqueId
                    </td>
                    <td>
                        @if(c.ForAll)
                        {
                            <span>For all products</span>
                        }
                        else if(c.ProductId != null)
                        {
                            <span>For product: @c.ProductName</span>
                        }
                        else if(c.VCategoryId != null)
                        {
                            <span>For V Category: @c.VCategoryCategoryName</span>
                        }
                        else if(c.HCategoryId != null)
                        {
                            <span>For H Category: @c.HCategoryCategoryName</span>
                        }
                    </td>
                    <td>
                        @c.Expires
                    </td>
                    <td>
                        @c.Discount %
                    </td>
                    @*<td>
                        @(c.Used ? "Yes" : "No") <a href="@Url.Action("SwitchUsed", new { id = c.CouponId })" class="btn btn-sm btn-default">switch</a>
                    </td>                    
                    <td>@Html.ActionLink("Download", "Download", "Coupon", new { id = c.CouponId}, new { @class = "btn btn-default" })</td>*@
                </tr>
            }
        </tbody>
    </table>
</div>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))