Marista.Admin/Controllers/BPRegController.cs
using Marista.Admin.Filters;
using Marista.Common.Tools;
using Marista.Common.ViewModels;
using Marista.DL;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Marista.Admin.Controllers
{

    public class BPRegController : BaseController
    {
        private readonly BPService db = new BPService();


        public async Task<ActionResult> Index()
        {
            var bpReg = await db.GetNew();
            return View(bpReg);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(BPRegVM rec)
        {
            if (Request.Files[0].ContentLength == 0)
            {
                ViewBag.AttachDocuments = true;
                var bpReg = await db.GetNew();
                rec.Countries = bpReg.Countries;
                rec.Leaders = bpReg.Leaders;
                return View("Index", rec);
            }


            MemoryStream target = new MemoryStream();

            Request.Files[0].InputStream.CopyTo(target);
            rec.Files = target.ToArray();
            rec.FileName = Request.Files[0].FileName;
            if (ModelState.IsValid)
            {
                int res = await db.Create(rec);
                if (res == 1)
                {
                    ViewBag.EmailUsed = true;
                    var bpReg = await db.GetNew();
                    rec.Countries = bpReg.Countries;
                    rec.Leaders = bpReg.Leaders;
                    return View("Index", rec);
                }
            }
            return RedirectToAction("Success");
        }

        public ActionResult Success()
        {
            return View();
        }


        public async Task<ActionResult> NotApproved()
        {
            var rec = await db.GetNotApproved();
            return View(rec);

        }

        public async Task<ActionResult> Approve(int bpId)
        {
            var bp = await db.Approve(bpId);
            var rec = await db.GetNotApproved();
            Parallel.Invoke(
            new Common.Tools.Mailer().SendMail(
                Server.MapPath("/Mails/approve.txt"),
                bp.EMail,
                "You are approved"
                ));

            return View("NotApproved", rec);

        }

        public async Task<ActionResult> Documents(int bpId)
        {
            var docs = await db.GetDocument(bpId);
            var fc = new FileContentResult(docs.Files, "application/octet-stream");
            fc.FileDownloadName = docs.FileName;
            return fc;
        }

        [HttpGet]
        public async Task<ActionResult> FilterBPs(SearchBPVM model)
        {
            if (model == null)
                model = new SearchBPVM();
            model.Countries = db.GetCountries();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> DoFilterBPs(SearchBPVM model)
        {
            await db.Search(model);
            return View("FilterBPs", model);
        }

        [HttpPost]
        public async Task<ActionResult> MailFilterBPs(SearchBPVM model)
        {
            ViewBag.ok = true;
            foreach (var item in Request.Form.AllKeys.Where(k => k.StartsWith("cbBP_")))
            {
                var bp = await db.GetBP(int.Parse(Request.Form[item]));
                Parallel.Invoke(() =>
                {
                    Common.Tools.Mailer.SendMailSpecific(model.MailText, bp.EMail,
                    "Mail from Marista");
                });

            }
            model.Countries = db.GetCountries();
            return View("FilterBPs", model);
        }


    }
}

Marista.Admin/Views/BPReg/FilterBPs.cshtml
@model Marista.Common.ViewModels.SearchBPVM

@{
    ViewBag.Title = "FilterBPs";
}

<div class="container chat-container">
    @using (Html.BeginForm("DoFilterBPs", "BPReg", FormMethod.Post))
    {
        <div id="chat-form-box" class="row">
            <div class="col-sm-2">
                Search:
            </div>
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.SS, new { @class = "form-control" })
            </div>
            <div class="col-sm-2">
                Country:
            </div>
            <div class="col-sm-3">
                @Html.DropDownListFor(m => m.CountryId, Model.Countries, "", new { @class = "form-control" })
            </div>
            <div class="col-sm-2">
                <button class="btn btn-primary" onclick="Search()">Search</button>
            </div>

        </div>
        <div id="chat-window" class="clearfix">
            @if (Model.BPs != null)
            {
                foreach (var item in Model.BPs)
                {
                    <div class="row">
                        <input type="checkbox" id="cbBP_@item.BPId" name="cbBP_@item.BPId" value="@item.BPId" />@item.BPName

                    </div>
                }
            }

            <div class="row">
                @Html.TextAreaFor(m => m.MailText, new { @class = "form-control" })
                <button class="btn btn-primary" onclick="Send()">Send</button>
                @if (ViewBag.ok == true)
                {
                    <div class="alert-info">Message sent!</div>
                }
            </div>
        </div>


    }
</div>
<script>
    function Send() {
        var form = $("form");
        $(form).attr('action', '/bpreg/MailFilterBPs').submit();
    }

    function Search() {
        var form = $("form");
        $(form).attr('action', '/bpreg/DoFilterBPs').submit();
    }
</script>

Marista.Admin/Views/BPReg/Index.cshtml
@model Marista.Common.ViewModels.BPRegVM

@{
    ViewBag.Title = "BPReg";
}
@section scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}
<div class="container">
    <div class="row">
        <div class="login-box col-sm-6 col-sm-offset-3 member-login-register-header text-center">
            <img src="/content/images/marista_club_logo.jpg">
        </div>
    </div>
    <div class="row">
        <div class="login-box col-sm-6 col-sm-offset-3">
            @using (Html.BeginForm("Create", "BPReg", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                if (ViewBag.AttachDocuments != null && ViewBag.AttachDocuments)
                {
                    <div class="text-danger">
                        Please, attach documents
                    </div>
                }
                if (ViewBag.EmailUsed != null && ViewBag.EmailUsed)
                {
                    <div class="text-danger">
                        Email already used
                    </div>
                }
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title text-center">
                            <h2>Brand Promoter Registration</h2>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="form-horizontal">

                            <div class="form-group">
                                @Html.LabelFor(model => model.BPName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.BPName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.BPName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.PayPal, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.PayPal, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.PayPal, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.CountryId, new SelectList(Model.Countries, "Value", "Text"), new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.LeaderId, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.LeaderId, new SelectList(Model.Leaders, "Value", "Text"), "---", new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LeaderId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Documents", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="file" name="file" />

                                </div>
                            </div>

                        </div>

                    </div>
                    <div class="panel-footer text-center">
                        <input type="submit" value="Save" class="btn btn-success btn-lg" />
                    </div>
                </div>

            }
        </div>
    </div>
</div>

Marista.Admin/Views/BPReg/NotApproved.cshtml
@model IList<Marista.Common.ViewModels.BPRegVM>

@{
    ViewBag.Title = "Index";
}

<h2>Not Approved</h2>
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th width="400">Files</th>
                <th width="100">Approve</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var b in Model)
            {
                <tr>
                    <td>@b.BPName</td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="@Url.Action("Documents", new { bpId = b.BPId})" class="btn btn-default" title="View"><i class="glyphicon glyphicon-search"></i></a>
                            @b.FileName
                        </div>
                    </td>
                    <td>
                        <a href="@Url.Action("Approve", new { bpId = b.BPId})" class="btn btn-default" title="View"><i class="glyphicon glyphicon-check"></i></a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Marista.Admin/Views/BPReg/Success.cshtml
@model Marista.Common.ViewModels.BPRegVM

@{
    ViewBag.Title = "BPReg";
}

<div class="container">
    <div class="row">
        <div class="login-box col-sm-6 col-sm-offset-3 member-login-register-header text-center">
            <img src="/content/images/marista_club_logo.jpg">
        </div>
    </div>
    <div class="row">
        <h2>Successful registration</h2>

    </div>
</div>