Marista.Admin/Controllers/ProductController.cs
using Marista.Admin.Filters;
using Marista.Common.ViewModels;
using Marista.DL;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Marista.Admin.Controllers
{
    [AdminAuthorize]
    public class ProductController : BaseController
    {
        private readonly ProductService _ps = new ProductService();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (this.UserData == null || (this.UserData != null && this.UserData.LevelId != 1))
            {
                filterContext.HttpContext.Response.Redirect(Url.Action("Login", "User"), true);
                return;
            }
            base.OnActionExecuting(filterContext);
        }

        public async Task<ActionResult> Index(string q, int? page)
        {
            var products = await _ps.Get(q);
            ViewBag.SearchQuery = q ?? string.Empty;
            return View(products.ToPagedList(page ?? 1, 20));
        }

        public async Task<ActionResult> Picture(int id)
        {
            var p = await _ps.Get(id);
            return File(p.Picture, "image/jpeg");
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var p = new ProductVM();
            await PopulateSelectLists();
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProductVM p)
        {
            if (ModelState.IsValid)
            {
                p.Picture = await GetUploadedFile("filePicture");
                if (p.Picture == null)
                {
                    ModelState.AddModelError("Picture", "Picture is required");
                }
                else
                {
                    p = await _ps.Create(p);
                    return RedirectToAction("Index", new { createdId = p.ProductId });
                }
            }
            await PopulateSelectLists();
            return View(p);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            var p = await _ps.Get(id);
            await PopulateSelectLists();
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProductVM p)
        {
            if (ModelState.IsValid)
            {
                // update the picture only if a new one is provided
                var picture = await GetUploadedFile("filePicture");
                if (picture != null)
                {
                    p.Picture = picture;
                }

                p = await _ps.Update(p);
                return RedirectToAction("Details", new { id = p.ProductId });
            }
            await PopulateSelectLists();
            return View(p);
        }

        public async Task<ActionResult> Details(int id)
        {
            var p = await _ps.Get(id);
            if (p == null)
            {
                return RedirectToAction("Index");
            }
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int productId)
        {
            try
            {
                await _ps.Delete(productId);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", new { });
            }
            return RedirectToAction("Index");
        }

        private async Task PopulateSelectLists()
        {
            ViewBag.HCategories = new SelectList(await _ps.GetHCategories(), "HCategoryId", "CategoryName");
            ViewBag.VCategories = new SelectList(await _ps.GetVCategories(), "VCategoryId", "CategoryName");
        }

        private async Task<byte[]> GetUploadedFile(string name)
        {
            var files = Request.Files;
            if (files.Count > 0)
            {
                var file = files[name];
                if (file != null && file.ContentLength > 0)
                {
                    using (var m = new MemoryStream())
                    {
                        await file.InputStream.CopyToAsync(m);
                        m.Position = 0;
                        return m.ToArray();
                    }
                }
            }
            return null;
        }


        public async Task<ActionResult> ProductPictures(int productId)
        {
            ViewBag.ProductId = productId;
            return View(_ps.GetProductPictures(productId));
        }

        public async Task<ActionResult> AddProductPicture(ProductPictureVM model)
        {

            MemoryStream target = new MemoryStream();
            string ext = Path.GetExtension(Request.Files[0].FileName).ToLower();
            model.IsVideo = ext == ".mp4" || ext == ".webm" || ext == ".ogg";
            Request.Files[0].InputStream.CopyTo(target);
            model.Picture = target.ToArray();
            _ps.AddProductPicrtue(model);

            return RedirectToAction("ProductPictures", new { productId = model.ProductId });
        }

        public async Task<ActionResult> DelProductPicture(int productPictureId)
        {
            int id = _ps.DelProductPicture(productPictureId);
            return RedirectToAction("ProductPictures", new { productId = id });
        }

        public async Task<ActionResult> GetProductPicture(int productPictureId)
        {
            return File(_ps.GetProductPicture(productPictureId), "application/octet-stream");
        }


    }
}

Marista.Admin/Controllers/RelatedProductController.cs
using Marista.Common.ViewModels;
using Marista.DL;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Marista.Admin.Controllers
{
    public class RelatedProductController : BaseController
    {
        private readonly ProductService _ps = new ProductService();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (this.UserData == null || (this.UserData != null && this.UserData.LevelId != 1))
            {
                filterContext.HttpContext.Response.Redirect(Url.Action("Login", "User"), true);
                return;
            }
            base.OnActionExecuting(filterContext);
        }

        public async Task<ActionResult> Index(string q, int? page)
        {
            var relatedProducts = await _ps.GetAllRelationships(q);
            ViewBag.SearchQuery = q ?? string.Empty;
            return View(relatedProducts.ToPagedList(page ?? 1, 20));
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var p = new RelatedProductVM();
            await PopulateSelectLists();
            return View(p);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RelatedProductVM p)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _ps.CreateRelated(p);
                    return RedirectToAction("Index");
                }
                catch(ArgumentException aex)
                {
                    ModelState.AddModelError(string.Empty, aex.Message);
                }
                catch(Exception)
                {
                    ModelState.AddModelError(string.Empty, "This relationship already exists");
                }
            }
            await PopulateSelectLists();
            return View(p);
        }

        public async Task<ActionResult> Delete(int fromProductId, int toProductId)
        {
            await _ps.DeleteRelated(fromProductId, toProductId);
            return RedirectToAction("Index");
        }

        private async Task PopulateSelectLists()
        {
            ViewBag.Products = new SelectList(await _ps.Get(), "ProductId", "Name");
        }
    }
}

Marista.Admin/Views/RelatedProduct/Create.cshtml
@model Marista.Common.ViewModels.RelatedProductVM

@{
    ViewBag.Title = "Create";
}
@section scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

@using (Html.BeginForm("Create", "RelatedProduct", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create new relationship</h4>
        
        @Html.Partial("_Edit")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success btn-lg" />
            </div>
        </div>
    </div>
}

<div class="sub-footer row">
    <div class="col-sm-12">
        <a href="@Url.Action("Index")" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-backward"></i> Back to the list of relationships</a>
    </div>
</div>

Marista.Admin/Views/RelatedProduct/Index.cshtml
@model PagedList.IPagedList<Marista.Common.ViewModels.RelatedProductVM>

@{
    ViewBag.Title = "Related Products";
}

<h2><a href="@Url.Action("Index")">@ViewBag.Title</a></h2>

<div class="row filters-panel">
    <div class="col-sm-3">
        <a href="@Url.Action("Create")" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Create a new relationship</a>
    </div>
    <div class="search-bar col-sm-4 col-sm-offset-5">
        <form action="@Url.Action("Index")" method="get" class="form-inline">
            <div class="form-group">
                <input type="search" name="q" value="@ViewBag.SearchQuery" class="form-control" placeholder="Search Related Products" />
                <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-filter"></i></button>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th></th>
                <th width="50%">Related Product</th>
                <th width="50%">Related To</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="@Url.Action("Delete", new { fromProductId = p.FromProductId, toProductId = p.ToProductId })" class="btn btn-danger btn-delete" title="Delete"><i class="glyphicon glyphicon-remove"></i></a>
                        </div>
                    </td>
                    <td class="accent"><a href="@Url.Action("Details", "Product", new { id = p.FromProductId })">@p.FromProductName</a></td>
                    <td class="accent"><a href="@Url.Action("Details", "Product", new { id = p.ToProductId })">@p.ToProductName</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))

Marista.Admin/Views/RelatedProduct/_Edit.cshtml
@model Marista.Common.ViewModels.RelatedProductVM

@Html.ValidationSummary(true, "", new { @class = "text-danger" })

<div class="form-group">
    @Html.LabelFor(model => model.FromProductId, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("FromProductId", (SelectList)ViewBag.Products, optionLabel: "Select product...", htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.FromProductId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.ToProductId, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("ToProductId", (SelectList)ViewBag.Products, optionLabel: "Select product...", htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ToProductId, "", new { @class = "text-danger" })
    </div>
</div>